spring.application.name=Senior Mentorship
spring.data.mongodb.uri=${MONGODB_URI}
server.error.whitelabel.enabled=false

# Before start Do this Work
# Set Your Api Key in .env file
# Set Your MongoDB URI in .env file
spring.ai.openai.api-key=${OPENAI_API_KEY}
